
[minecraft]
	replace_wolf = true
	replace_polar_bear = true
	replace_sheep = true
	replace_cat = true
	replace_spider = true
	replace_dolphin = true
	replace_skeleton_horse = true
	replace_zombie_horse = true
	replace_chicken = true
	replace_donkey = true
	replace_cow = true
	replace_horse = true
	replace_mooshroom = true
	replace_cavespider = true
	replace_pig = true
	replace_ocelot = true
	replace_fox = true
	replace_squid = true
	replace_mule = true
	replace_silverfish = true
	replace_bee = true

