
#Mod integration config
[Integration]

	#Minecraft
	[Integration.minecraft]

		#Vanilla Minecraft
		[Integration.minecraft.minecraft]
			#Enabled Vanilla Minecraft integration. Default value is true
			enabled = true

	#Create
	[Integration.create]

		#Create Creative Crate
		[Integration.create.creative_crate]
			#Create Creative Crate storage priority. Items are inserted first into storages with higher priority. Default value is 0
			priority = 0
			#Enabled Create Creative Crate integration. Default value is true
			enabled = true

		#Create Crate
		[Integration.create.crate]
			#Create Crate storage priority. Items are inserted first into storages with higher priority. Default value is 0
			priority = 0
			#Enabled Create Crate integration. Default value is true
			enabled = true

	#Iron Chests
	[Integration.ironchest]

		#Iron Chests
		[Integration.ironchest.chest]
			#Enabled Iron Chests integration. Default value is true
			enabled = true

	#Storage Drawers
	[Integration.storagedrawers]

		#compacting drawers
		[Integration.storagedrawers.compacting_drawer]
			#compacting drawers storage priority. Items are inserted first into storages with higher priority. Default value is 10
			priority = 10
			#Enabled compacting drawers integration. Default value is true
			enabled = true

		#standard drawers
		[Integration.storagedrawers.drawer]
			#standard drawers storage priority. Items are inserted first into storages with higher priority. Default value is 10
			priority = 10
			#Enabled standard drawers integration. Default value is true
			enabled = true

